/*
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tt1.trabajo.utilidades;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Solicitud
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T17:18:13.175597100+02:00[Europe/Berlin]", comments = "Generator version: 7.5.0")
public class Solicitud {
  public static final String SERIALIZED_NAME_CANTIDADES_INICIALES = "cantidadesIniciales";
  @SerializedName(SERIALIZED_NAME_CANTIDADES_INICIALES)
  private List<Integer> cantidadesIniciales;

  public static final String SERIALIZED_NAME_NOMBRE_ENTIDADES = "nombreEntidades";
  @SerializedName(SERIALIZED_NAME_NOMBRE_ENTIDADES)
  private List<String> nombreEntidades;

  public Solicitud() {
  }

  public Solicitud cantidadesIniciales(List<Integer> cantidadesIniciales) {
    this.cantidadesIniciales = cantidadesIniciales;
    return this;
  }

  public Solicitud addCantidadesInicialesItem(Integer cantidadesInicialesItem) {
    if (this.cantidadesIniciales == null) {
      this.cantidadesIniciales = new ArrayList<>();
    }
    this.cantidadesIniciales.add(cantidadesInicialesItem);
    return this;
  }

   /**
   * Get cantidadesIniciales
   * @return cantidadesIniciales
  **/
  @javax.annotation.Nullable
  public List<Integer> getCantidadesIniciales() {
    return cantidadesIniciales;
  }

  public void setCantidadesIniciales(List<Integer> cantidadesIniciales) {
    this.cantidadesIniciales = cantidadesIniciales;
  }


  public Solicitud nombreEntidades(List<String> nombreEntidades) {
    this.nombreEntidades = nombreEntidades;
    return this;
  }

  public Solicitud addNombreEntidadesItem(String nombreEntidadesItem) {
    if (this.nombreEntidades == null) {
      this.nombreEntidades = new ArrayList<>();
    }
    this.nombreEntidades.add(nombreEntidadesItem);
    return this;
  }

   /**
   * Get nombreEntidades
   * @return nombreEntidades
  **/
  @javax.annotation.Nullable
  public List<String> getNombreEntidades() {
    return nombreEntidades;
  }

  public void setNombreEntidades(List<String> nombreEntidades) {
    this.nombreEntidades = nombreEntidades;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Solicitud solicitud = (Solicitud) o;
    return Objects.equals(this.cantidadesIniciales, solicitud.cantidadesIniciales) &&
        Objects.equals(this.nombreEntidades, solicitud.nombreEntidades);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(cantidadesIniciales, nombreEntidades);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Solicitud {\n");
    sb.append("    cantidadesIniciales: ").append(toIndentedString(cantidadesIniciales)).append("\n");
    sb.append("    nombreEntidades: ").append(toIndentedString(nombreEntidades)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cantidadesIniciales");
    openapiFields.add("nombreEntidades");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Solicitud
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Solicitud.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Solicitud is not found in the empty JSON string", Solicitud.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Solicitud.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Solicitud` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("cantidadesIniciales") != null && !jsonObj.get("cantidadesIniciales").isJsonNull() && !jsonObj.get("cantidadesIniciales").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `cantidadesIniciales` to be an array in the JSON string but got `%s`", jsonObj.get("cantidadesIniciales").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("nombreEntidades") != null && !jsonObj.get("nombreEntidades").isJsonNull() && !jsonObj.get("nombreEntidades").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `nombreEntidades` to be an array in the JSON string but got `%s`", jsonObj.get("nombreEntidades").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Solicitud.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Solicitud' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Solicitud> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Solicitud.class));

       return (TypeAdapter<T>) new TypeAdapter<Solicitud>() {
           @Override
           public void write(JsonWriter out, Solicitud value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Solicitud read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Solicitud given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Solicitud
  * @throws IOException if the JSON string is invalid with respect to Solicitud
  */
  public static Solicitud fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Solicitud.class);
  }

 /**
  * Convert an instance of Solicitud to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

